Jie/hotspots fluctuation ready to merge with main branch
Non-Equilibrium-QCD/McDipper pull request #5
Opened 2024-09-04 08:45 UTC by zhujie12138

Implement the Thickness fluctuation and Hotspots fluctuation

2024-09-17 14:04 UTC, thegarzo requested changes

2024-09-17 14:04 UTC, thegarzo commented on Makefile
> -LIBS          = -I/usr/local/include -L/usr/local/lib -lgsl -lgslcblas -lcuba -lm `lhapdf-config --cflags --ldflags`#-lcuba -lm
This needs to be returned to the original makefile.

2024-09-17 14:04 UTC, thegarzo commented on configs/ipsat.yaml
> +        Bq: 0.04
Check what happens when Bq and Nq are not given.

2024-09-18 20:19 UTC, zhujie12138 commented on Makefile
> -LIBS          = -I/usr/local/include -L/usr/local/lib -lgsl -lgslcblas -lcuba -lm `lhapdf-config --cflags --ldflags`#-lcuba -lm
Done

2024-09-18 20:21 UTC, zhujie12138 commented on configs/ipsat.yaml
> +        Bq: 0.04
I Added few lines in nucleus.cpp to terminate the program when Nq, Bq or sigma are not given or inappropriate.

2024-10-18 16:04 UTC, thegarzo commented on configs/ipsat.yaml
> +        Bq: 0.04
Ok , perfect

2024-10-18 16:05 UTC, thegarzo approved these changes

2024-10-18 16:05 UTC, merged